### PR TITLE
implement a post_simulation hook

### PR DESCRIPTION
**Pull request by zingale**
this is the start of a generic `post_simulation()` function called at the end of the simulation.

### CODE REVIEW

**Comment by zingale** [comment]
This now addresses #108 and #107

**Comment by zingale** [comment]
Last style bit:

I put `post_simulation()` in `Prob.cpp`, but some problem setups already have their own `Prob.cpp`.  Therefore, either I need to:

* ifdef this functionality out (don't really like that)
* put it in a different file (like `Prob_post.cpp`)
* update all of the setups that have their own `Prob.cpp` to have the needed stub

**Comment by maxpkatz** [comment]
Regarding the style question: until now, newly added problem hooks of this sort have been ifdef'd out with an additional preprocessor macro associated with each one. I am not necessarily particularly proud of this convention but it is the one we've got at present. I would be OK with putting it in a separate file. I am not OK with breaking compatibility by putting it on Prob.cpp without a preprocessor macro wrapped around it.

**Comment by maxpkatz** [comment]
Note though that if you take the route of putting it in a different file, it has to be unique file just for that function. If we started adding things to do it in the future we would then be breaking compatibility again.  That's why there's at least some argument for the preprocessor approach.

**Pull request merged**
