### PR TITLE
merge computeTemp from radiation to hydro

### PR DESCRIPTION
**Pull request by zingale**
This PR removes the radiation-specific version of the `computeTemp` function and instead has everything go through the hydro version.  There are some minor differences in how the internal energy is handled now for radiation for resets (e.g., it now does the same thing pure hydro does, which is a good thing).

Also, there is no test coverage of the `do_real_eos=0` option for radiation, but I _believe_ that code is accurately changed over.

Wait until the test suite finishes before we merge this (assuming that the differences are reasonable)

### CODE REVIEW

**Comment by zingale** [comment]
Here are the test suite results:

http://bender.astro.sunysb.edu/Castro/test-suite/test-suite-gfortran/2016-12-05-002/index.html

errors look reasonable to me.

**Comment by zingale** [comment]
Okay, the tests of the `do_real_eos = 0` don't show any changes.  The other tests show changes ~ 1.e-5 level.

okay to merge this?

**Comment by maxpkatz** [comment]
LGTM

**Comment by zingale** [comment]
closes #64

**Pull request merged**
